#!/bin/sh

# 该脚本执行的时候 是在 .git/hooks目录下，因此，一下目录都已该目录计算
unset GIT_DIR
cd `dirname $0`
CURDIR=`pwd`

# 到达git根目录
cd ../../
GITPATH=`pwd`

#  得到服务器地址
host=`cat package.json|grep '_serverHost'|tr -s [:space:]|cut -f 4 -d '"'`
port=`cat package.json|grep '_serverPort'|tr -s [:space:]|cut -f 4 -d '"'`

sh _server/request-update.sh &
